import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { SignInButtonStyled, SignOutButtonStyled, SignUpButtonStyled } from "~/components/buttons";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data, isLoading, isSuccess, isError } = api.farms.getAll.useQuery();

  const user = useUser();

  useEffect(() => {
    console.log(user);
  }, [user]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-white">
        {!user.isSignedIn && (
          <>
            <SignInButtonStyled />
            <SignUpButtonStyled />
          </>
        )}
        {!!user.isSignedIn && <SignOutButtonStyled />}
        {user.user?.fullName}

        {data &&
          isSuccess &&
          data.map((farm) => <div key={farm.id}>{farm.name}</div>)}
      </main>
    </>
  );
};

export default Home;
