import { ReactElement } from "react";
import { Footer } from "./footer";
import { Header } from "./header";
import Head from "next/head";

export const Layout = ({
  children,
}: {
  children: ReactElement | ReactElement[];
}) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="flex flex-1 flex-col items-center justify-center bg-white">
        {children}
      </main>
      <Footer />
    </>
  );
};
